#!/usr/bin/env bash
set -e

echo "# Uploading to s3..."

upload_files()
{
  pushd "$1" > /dev/null
  for i in AlphaSans*
  do
    aws s3 cp "$i" "s3://alphaprime-s3/AlphaSans/${i//$2/$3}"
  done
  popd
}

upload_files "Subset" AlphaSans AlphaSans
aws s3 cp "./css/alpha-sans.css" "s3://alphaprime-s3/AlphaSans/alpha-sans.css"

aws cloudfront create-invalidation --distribution-id "$AWS_DISTRIBUTION_ID" --paths /AlphaSans\*
